### ISSUE TITLE
add 'pixel' as unit?

### ISSUE THREAD

**Issue by huangziwei** [ppinard/matplotlib-scalebar#12]
Hi, 

Sometimes I don't really know the unit of the picture and the axis is turned off for aesthetic reason. It would be nice to have a scale bar just for showing how many pixels a certain length of the picture spanned.

**Comment by ppinard** [comment]
That's a very good idea. One question about whether to allow prefixes (e.g. npx, mpx, kpx, Mpx)? I guess maybe kpx (kilo-pixel) and Mpx (mega-pixel) make sense for large maps, but prefixes for less than 1 (e.g. micro, nano) would never arise?

**Comment by huangziwei** [comment]
I guess px, kpx, Mpx will cover most of the use scenarios, while the others can be added by future requests? Actually I never see mpx and npx in real life...

**Comment by ppinard** [comment]
Sorry the delay. I completely forgot about this issue. The code is in and I will create a new release soon.
