### ISSUE TITLE
Draw the scalebar without any text

### ISSUE THREAD

**Issue by pskeshu** [ppinard/matplotlib-scalebar#13]
I'm trying to plot just a scalebar without any associated text that says what's the length and unit of scale bar. What's the best way to do this?

**Comment by AKuederle** [comment]
If I remember correctly, you could use the label formatter and just pass it
an empty string

**Comment by AKuederle** [comment]
To be more precise. I think you would pass a function that returns an empty
string, because the label formatter is passed the scale and the unit. So as
argument of the scalebar you can set :

```
label_formatter=lambda x: ''
```

**Comment by pskeshu** [comment]
Thanks @AKuederle! 😃  

Although I had to use `label_formatter = lambda x, y:''`. I was previously trying `scalebar.label_formatter('', '')` which didn't work as expected.

**Comment by habi** [comment]
One thing that worked for me was setting the label text to size zero with `font_properties={'size':0}`.

**Comment by shuzokato** [comment]
Thanks for the information.
As of 2022, `scale_formatter=lambda x, y:''` works for this because 'label_formatter' is deprecated.

**Comment by ppinard** [comment]
Actually as of 2022, it is easier to do set `scale_loc` and `label_loc` to `"none"`. Note not `None`, but a string `none`.
