### ISSUE TITLE
print statement in scalebar.py

### ISSUE THREAD

**Issue by wiai** [ppinard/matplotlib-scalebar#18]
Hi Philippe,
there is a print() statement in line 322 of scalebar.py which leads to some uncalled-for output e.g. in jupyter notebooks etc. when using the scalebar. I guess this is left over from debugging/testing and could be removed...
Best regards,
Aimo.

**Comment by ppinard** [comment]
Thank you. Yes I forgot to remove this when I was debugging issue #14. The fix is in 9eeebf73ae18963e3f3ec0b743d90acc5fbbe56a. I will create a new release soon.
