### ISSUE TITLE
Please add a link to third-party-packages on matplotlib docs

### ISSUE THREAD

**Issue by tacaswell** [ppinard/matplotlib-scalebar#21]
This looks very useful!  Could you add a blurb like those at 
https://matplotlib.org/thirdpartypackages/index.html (source is at 
https://github.com/matplotlib/matplotlib/blob/master/doc/thirdpartypackages/index.rst) ?

**Comment by ppinard** [comment]
Thank you for the suggestion. I guess matplotlib-scalebar would fit under the section "Specialty plots"?

**Comment by tacaswell** [comment]
I agree it would fit there.

**Comment by ppinard** [comment]
Added in PRs matplotlib/matplotlib#15537 and matplotlib/matplotlib#15561
