### ISSUE TITLE
font_properties arg acts unexpected 

### ISSUE THREAD

**Issue by maweigert** [ppinard/matplotlib-scalebar#3]
The font_properties argument in the ScaleBar constructor behaves different from the doc 

```
from matplotlib.font_manager import FontProperties
gca().add_artist(ScaleBar(.1, font_properties=FontProperties(size = 12)))
```

results in an error ("TypeError: 'FontProperties' object is not iterable").

I assume the reason is in the line

https://github.com/ppinard/matplotlib-scalebar/blob/562363b003dd1bee0592ede4c05f6d687fb2f99e/matplotlib_scalebar/scalebar.py#L154
which is 

```
self.font_properties = FontProperties(font_properties)
```

but should be 

```
self.font_properties = font_properties
```

(after changing that, everything works fine)

PS:
Thanks for the package!

**Comment by joschkazj** [comment]
I've run into the same issue, see #2 for the currently suggested solution.

**Comment by ppinard** [comment]
In new release version 0.2.0 on PyPi
