### ISSUE TITLE
text above scale bar

### ISSUE THREAD

**Issue by gazzar** [ppinard/matplotlib-scalebar#31]
Hi, Is it currently possible to place the text above the scale bar? The README mentions setting the scalebar.label_top rcParam but there is no reference to this in the code and it doesn't seem to do anything when I try it. I'm also unclear on what the scale_loc and label_loc parameters are for; I don't see any effect from those.

-- edit --

Just after creating this question, I discovered that I can enter a negative value for the sep parameter and this places the text above the scalebar. I don't suppose this is intentional but I'll do this as a workaround for the moment.

**Comment by ppinard** [comment]
@gazzar Hi, there is an error in the README. There is no `label_top` parameter but a `label_loc`. I am a bit unclear why you don't see any effect for `label_loc` and `scale_loc`. To show the differences I created this demo code:

```python
import matplotlib.pyplot as plt
from matplotlib_scalebar.scalebar import ScaleBar

plt.figure()
plt.gca().add_artist(
    ScaleBar(
        0.5,
        label="scale_loc=top, label_loc=top",
        scale_loc="top",
        label_loc="top",
        location="upper right",
    )
)
plt.gca().add_artist(
    ScaleBar(
        0.5,
        label="scale_loc=bottom, label_loc=top",
        scale_loc="bottom",
        label_loc="top",
        location="lower right",
    )
)

plt.gca().add_artist(
    ScaleBar(
        0.5,
        label="scale_loc=top, label_loc=bottom",
        scale_loc="top",
        label_loc="bottom",
        location="upper left",
    )
)
plt.gca().add_artist(
    ScaleBar(
        0.5,
        label="scale_loc=bottom, label_loc=bottom",
        scale_loc="bottom",
        label_loc="bottom",
        location="lower left",
    )
)

plt.savefig("example1.png")
```

It produces this figure:
![example1](https://user-images.githubusercontent.com/715280/88479922-999db300-cf4a-11ea-8934-d2facbb28810.png)

Please let me know if you need more explanations.

**Comment by gazzar** [comment]
Thanks Philippe,
Just returning to this now, I can't exactly remember what I tried, but I think my confusion came from thinking that what you refer to as the scale was the label. Since I didn't have a label, setting the label_loc was doing nothing when I was expecting that to affect the scale position. Your example clarifies things
