### ISSUE TITLE
Fine adjustment of the scalebar position.

### ISSUE THREAD

**Issue by altanir84** [ppinard/matplotlib-scalebar#39]
Is there a way to fine adjust the scalebar position? I need to place the scalebar at the lower right of a image, but there is a label that also needs to be there and I´d like to raise the scalebar a few pixels, so both will be on the lower right but not overlapping each other.

**Comment by hakonanes** [comment]
Hi @altanir84, you could perhaps pass `border_pad`?

```python
>>> import matplotlib.pyplot as plt
>>> from matplotlib_scalebar.scalebar import ScaleBar
>>> import numpy as np
>>> a = np.random.normal(size=100).reshape((10, 10))
>>> legend_kwds = dict(x=8, y=9, s="legend", bbox=dict(facecolor="w"))
>>> fig, ax = plt.subplots(ncols=2, figsize=(10, 5))
>>> ax[0].imshow(a)
>>> ax[0].text(**legend_kwds)
>>> ax[0].add_artist(ScaleBar(1, "px", dimension="pixel-length", location="lower right"))
>>> ax[1].imshow(a)
>>> ax[1].text(**legend_kwds)
>>> ax[1].add_artist(ScaleBar(1, "px", dimension="pixel-length", location="lower right", border_pad=3))
```

![matplotlib_scalebar_border_pad_example](https://user-images.githubusercontent.com/12139781/117988261-88882c00-b33b-11eb-8b2c-1a9d0e4df2b9.png)

Horizontal and vertical padding will be the same, which isn't optimal, but you can at least move it diagonally away from the lower right corner. Actually, I think you might be better off setting changing the legend position.

**Comment by altanir84** [comment]
Thank you for the quick reply.

I´ve tried passing the border_pad argument, but the problem is that I´m working on generating thousands of images with a strict layout and I can´t change that because of the company´s layout standards for such images. I was looking for something like tkinter´s pady and padx.

**Comment by altanir84** [comment]
So, I managed to get it working by downloading the scalebar.py and dimensions.py to my working folder and changed somethings to enable the bbox_to_anchor argument to be passed. I guess it could be a future update to the module!

What I did:

Open scalebar.py

class ScaleBar(Artist):
def __init__(
... 

add this after _rotation=None_ :

        bbox_to_anchor=None,  # bbox that the legend will be anchored.
        bbox_transform=None,  # transform for the bbox

add this after _self.rotation = rotation_ :

        self.bbox_to_anchor = bbox_to_anchor
...
def draw(self,renderer,*args,**kwargs):

add this after _label = self.label_ :

        bbox_to_anchor = self.bbox_to_anchor

now scroll down to _# Create final offset box_  :

     We need to insert a if-else statement, to verify if the argument bbox_to_anchor was passed. Place
it just before the _box = AnchoredOffsetbox(_ and mind the indentation.

            if bbox_to_anchor != None:
                box = AnchoredOffsetbox(loc=location, pad=pad,  child=child, frameon=frameon, 
                                                            bbox_to_anchor=bbox_to_anchor, bbox_transform=ax.transAxes
                            )
            else:


save it and place both py files on the work dir and import it using 

from scalebar import ScaleBar.

Now the ScaleBar can take a tuple to define where the scalebar will be placed.

**Comment by hakonanes** [comment]
Great! I suppose passing `bbox_to_anchor` overrides `location`?

**Comment by altanir84** [comment]
Oops, sorry! I forgot to remove the location argument. When using both, weird stuff happens. It´s better to use only one of them.

If the module gets updated to use bbox_to_anchor in the future, great. If not, this workaround can be used.

**Comment by ppinard** [comment]
Actually, the `location` has a big influence on the output when using `bbox_to_anchor`. I modified the documentation accordingly and added an example in #40 (reproduced here below).

```python
fig, ax = plt.subplots()

scalebar = ScaleBar(
    1,
    "cm",
    length_fraction=0.25,
    bbox_to_anchor=(0.5, 0.5),
    bbox_transform=ax.transAxes,
    location="lower left",
    label="lower left",
    box_color="0.8",
)
ax.add_artist(scalebar)

scalebar = ScaleBar(
    1,
    "cm",
    length_fraction=0.25,
    bbox_to_anchor=(0.5, 0.5),
    bbox_transform=ax.transAxes,
    location="upper right",
    label="upper right",
    box_color="0.8",
)
ax.add_artist(scalebar)
```
![argument_bbox_to_anchor](https://user-images.githubusercontent.com/715280/219974556-c66a11e1-faf2-42cd-93f2-bbb46d06cbf7.png)
