### ISSUE TITLE
Option to add scalebar without scale 

### ISSUE THREAD

**Issue by bugalo** [ppinard/matplotlib-scalebar#41]
It is sometimes useful to have a scalebar without scale or label, just the line. For example, if you already mention the scale in the figure caption. I have not found a way to hide the scale. Is it possible to implement it?

Thanks.

**Comment by ppinard** [comment]
Thank you for the issue. I implemented your suggestion in #46.

![image](https://user-images.githubusercontent.com/715280/143687658-ff79bad4-9975-479d-bc6d-c0e4f113c644.png)
