### ISSUE TITLE
Readme : Specify micrometer?

### ISSUE THREAD

**Issue by kolibril13** [ppinard/matplotlib-scalebar#43]
It is easy to specify the size in centimeter "cm" and nanometer "nm".
But how can I use micrometer?
![image](https://user-images.githubusercontent.com/44469195/128865369-7bec1673-0ded-4aaa-a730-a7e3fec5ef16.png)

**Comment by hakonanes** [comment]
Should be as simple as specifying `units="um"` with `dimension="si-length"`

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib_scalebar.scalebar import ScaleBar
fig, ax = plt.subplots()
ax.imshow(np.random.normal(size=100).reshape((10, 10))
ax.add_artist(ScaleBar(1, units="um", dimension="si-length"))
```

**Comment by kolibril13** [comment]
nice, thanks!
