### ISSUE TITLE
Scale Bar - Example Gallery 

### ISSUE THREAD

**Issue by kolibril13** [ppinard/matplotlib-scalebar#49]
Hi @ppinard!
I've just written an example gallery for the matplotlib-scalebar package:  
 https://kolibril13.github.io/plywood-gallery-matplotlib-scalebar/ 
One can click on one image and the corresponding code will be displayed.
Feedback is welcome!
What do you think about mentioning this gallery in the readme?
<img width="610" alt="image" src="https://user-images.githubusercontent.com/44469195/200573911-21dc9deb-89bb-406f-b8b5-7bba8d261bba.png">

**Comment by ppinard** [comment]
Thank you for the contribution and apologies for not merging the PR sooner.
