### ISSUE TITLE
Warning Issued on calling Scalebar

### ISSUE THREAD

**Issue by bidhya** [ppinard/matplotlib-scalebar#5]
Every time I import ScaleBar as here, 
`%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib_scalebar.scalebar import ScaleBar`

I get the following warning

_C:\\Anaconda2\lib\site-packages\matplotlib\__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
  warnings.warn(_use_error_msg)_

Can you please check what is going on here. I am on Windows 10 with Anaconda 32 bit Python 2.7

**Comment by ppinard** [comment]
Thank you for reporting this issue. To help me understand it, could you let me know which version of _matplotlib_ and _ipython_ are you using? 

```python
import matplotlib
matplotlib.__version__
import IPython
IPython.__version__
```

**Comment by bidhya** [comment]
matpotlib version = 1.5.3
IPython version     = 5.1.0
Please let me know @ppinard if you need more information to resolve this issue.

**Comment by ppinard** [comment]
Close as this has not been since for a while.
