### ISSUE TITLE
dimensions="imperial-length" won't display in Miles unless sufficiently zoomed out

### ISSUE THREAD

**Issue by DariyaGIN** [ppinard/matplotlib-scalebar#54]
I am in the USA, and few people here are good at meters / kilometers, so I do have to use the Scalebar's imperial-length dimension when creating maps in geopandas.  Unfortunately, the scale won't stay in miles if you are zoomed in such that the extent of the map is now at a sub-mile level.  So at that point the scalebar shows furlongs or chains instead of fractions of a mile, and furlongs and chains are not something anyone here is familiar with.  

It would be very nice to be able to display in fractions of a mile (to the tenth's place, unless it is 0.25 or 0.75) instead of in furlongs or chains.  It also works to display in feet (10ft, 30ft, 50ft, 100ft, 200ft, 500ft, 1000ft, 2000ft). I really hope this can be a feature that is added to this otherwise wonderful scalebar.  

I've attached this map as an example of how the scalebar displays chains (ch) or furlongs (fur) instead of miles or feet:
![PeninsulaOpenSpaceTrust_Sonntag](https://user-images.githubusercontent.com/118312916/219145577-316c8aeb-3693-4717-a89a-5f56cf912df6.png)

**Comment by ppinard** [comment]
That is a very good point. Furlong, chain, league and even yard are probably not very common in most circumstances. I think I included everything on Wikipedia (https://en.wikipedia.org/wiki/Imperial_units#Length) without thinking!

```python
class ImperialLengthDimension(_Dimension):
    def __init__(self):
        super().__init__("ft")
        self.add_units("th", 1 / 12000)
        self.add_units("in", 1 / 12)
        self.add_units("yd", 3)
        self.add_units("ch", 66)
        self.add_units("fur", 660)
        self.add_units("mi", 5280)
        self.add_units("lea", 15840)
```

If you have a change could check that in your example, this custom dimension would work?


```python
from matplotlib_scalebar.dimension import _Dimension
from matplotlib_scalebar.scalebar import ScaleBar

class ImperialLengthDimension2(_Dimension):
    def __init__(self):
        super().__init__("ft")
        self.add_units("th", 1 / 12000)
        self.add_units("in", 1 / 12)
        self.add_units("mi", 5280)

scalebar = ScaleBar(dx, ImperialLengthDimension2())
```

**Comment by DariyaGIN** [comment]
It works!!!  ^_^ 
![PeninsulaOpenSpaceTrust_CPADUnit_Sonntag](https://user-images.githubusercontent.com/118312916/221019342-a6ff2df7-2bba-45f1-8fe1-eea794a9c9ab.png)

Thank you so very much for taking the time to provide a solution and to respond to this issue.  Have a great day :).
