### ISSUE TITLE
Latex representation mu does not work

### ISSUE THREAD

**Issue by AKuederle** [ppinard/matplotlib-scalebar#6]
Hey, it looks like the latex representation of micro does not work, because the _Dimension.calculate_preferred will overwrite the "µm" unit with "um".

I fixed it by monkey patching this method for now, but I a proper solution would be better :D

**Comment by ppinard** [comment]
I uploaded a fix in commit 5d625dac174eb5893c55b6cea8174201fdbe6b91. The problem was that a latex representation was only defined for the unicode notation (i.e. `u00b5`) and not for `u`. Please let me know if I can close this issue.

**Comment by AKuederle** [comment]
Works perfectly! Thank you very much!
