### ISSUE TITLE
Reloading matplotlib overwrites custom settings

### ISSUE THREAD

**Issue by AKuederle** [ppinard/matplotlib-scalebar#7]
Hi it seems like reloading matplotlib using ```imp``` as you do on line 81 in ```scalebar.py``` causes some issues with custom settings.
For example:

```python
from matplotlib_scalebar.scalebar import ScaleBar
from matplotlib_scalebar.dimension import _Dimension
import matplotlib as mpl

import matplotlib.pyplot as plt
mpl.rcParams.update({'font.family': 'serif'})
```
will lead to 
![image](https://cloud.githubusercontent.com/assets/10776763/23097117/3538f186-f62c-11e6-8da6-f50ad1e0b746.png)

As you can see the fonts are sans-serif and not serif.
Doing the same without importing matplotlib_scalebar, will lead to the expected result:

```python
# from matplotlib_scalebar.scalebar import ScaleBar
# from matplotlib_scalebar.dimension import _Dimension
import matplotlib as mpl

import matplotlib.pyplot as plt
mpl.rcParams.update({'font.family': 'serif'})
```
![image](https://cloud.githubusercontent.com/assets/10776763/23097125/7556059c-f62c-11e6-869b-0d1c30012cc5.png)

By playing around with a local install of your package I could verify, that reloading matplotlib (line 81) causes this issue.
```python
imp.reload(sys.modules['matplotlib'])
```
Removing that line resolves the issue and does not seem to change anything else. (all test still work and all other things I tested, too)
Could you explain what the original intention of this line was?

Best regards,
Arne

(PS: awesome package otherwise! Saved me a lot of time!)

**Comment by ppinard** [comment]
Thank you for reporting the issue. The intention of the `imp.reload(...)` is to allow the definition of new parameters in matplotlibrc. For instance, if you comment out line 81, the following throws an error:

```python
matplotlib.rcParams['scalebar.box_color'] = 'r'

KeyError: 'scalebar.box_color is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'
```

I tried another approach in commit db3d48bb4b2c4f34fed5688f91ad7093cb0c724d where I only reload the `validate` method from `RcParams`. It seems to fix the problem, but please let me know if you find other limitations.

**Comment by AKuederle** [comment]
Thank you very much for fixing this so fast! From my side it looks like it is working.
