### ISSUE TITLE
Force certain scale bar length

### ISSUE THREAD

**Issue by habi** [ppinard/matplotlib-scalebar#9]
First; thanks for making this!

I'm plotting several images together in a subplot, as seen in the image below (for *science* reasons some information is blurred).

![issue](https://cloud.githubusercontent.com/assets/1651235/25751286/bee56bbc-31b4-11e7-8b24-3ec79840809d.png)

For sake of consistency I'd like to have a 1 mm scale bar on all the images.
Is this possible?

**Comment by habi** [comment]
I suspect the `label_formatter` is used for this, but I cannot seem to find out how...

**Comment by ppinard** [comment]
No the `label_formatter` won't do what you are looking for. It only changes the way the text is displayed and not the length of the scale bar. I think what you described would be a very nice addition but I have to think the proper way of implementing it. 

I guess the constructor would need two additional arguments: `desired_value` and `desired_unit`. In your example, `deaired_value=1` and `desired_unit='mm'`. I am just wondering what would happen if someone selects a combination where the scale bar is either too long for the subplot or too small to be visible.

**Comment by habi** [comment]
> I am just wondering what would happen if someone selects a combination where the scale bar is either too long for the subplot or too small to be visible.

I have no idea if this is feasible, but maybe one could issue a warning if the `length_fraction` goes towards one or is smaller than 0.05.

**Comment by habi** [comment]
Thanks for implementing this (in [the relevant branch](https://github.com/ppinard/matplotlib-scalebar/tree/fixed_value)), it works as intended!
Attached is an overview of several differently sized images (again, blurred for science reasons) which all have the same-length scale bar on them.
![scalebars](https://user-images.githubusercontent.com/1651235/28209864-d07fd698-6894-11e7-84dd-83faad91075d.png)

**Comment by pskeshu** [comment]
Works as expected! I ❤️ matplotlib-scalebar! :D
